### ISSUE TITLE
unexpected async reset

### ISSUE THREAD

**Issue by taylor-bsg** [bsg-external/HardFloat#16]
https://github.com/bsg-external/HardFloat/blob/f75f8f573230a4d2627d2c404599998d6d6ae475/source/divSqrtRecFN_small.v#L170

ZynqParrot was complaining about this with Vivado 2022.1

**Comment by taylor-bsg** [comment]
@dpetrisko @tommydcjung  can you take a look?  looks like BP uses this module, does HB use it?

**Comment by dpetrisko** [comment]
Yeah I’ve seen this in Verilator warnings as well. We should go through and convert everything to sync reset

**Comment by dpetrisko** [comment]
Oh in fact #6

**Comment by dpetrisko** [comment]
Fixed!
