### ISSUE TITLE
Make clear that this is a modified version of HardFloat

### ISSUE THREAD

**Issue by jhauser-us** [bsg-external/HardFloat#29]
Update the README files and probably elsewhere to make clear at the top that this is a copy of Berkeley HardFloat that has been modified by Bespoke Silicon Group.

While it may not be intentional, you are currently committing a kind of fraud by giving people the impression that this repository is an officially maintained version of Berkeley HardFloat.  You have an ethical obligation to fix that, maybe even a legal obligation.  Please do so.

**Comment by dpetrisko** [comment]
Updated! Originally this was a straight mirror, but we should certainly have put modifications on a labeled branch to differentiate. Sorry for any confusion!

**Comment by jhauser-us** [comment]
I appreciate the prompt response.  I request similarly editing "README.html".

**Comment by dpetrisko** [comment]
Updated the other two readmes as well!
